// Curated learning content. Star positions/lines come from data.js; this file is the "teacher".
// deck: which starter deck the constellation belongs to.
// cue: the visual signature to lock onto (pattern recognition).
// find: star-hop directions from something easier.
// story: a hook for memory (dual coding: shape + narrative).
// confuse: constellations people mix it up with (used to pick hard foils).
// best: evening viewing month(s), Northern-hemisphere reference unless noted.
window.SKY_CONTENT = {
  // One pool. Order = the order new cards are introduced: bright, famous shapes first.
  order: ['UMa','Ori','Cas','Sco','Leo','Cyg','Lyr','UMi','Tau','Gem','CMa','Boo','Sgr','Aql','Peg','Cru','Cen','Aur','Per','Vir','And','Her','CrB','CMi','Dra','Cep','Ari','Del','Lep','Crv','Hya','Oph','Car','Lib','Cap','Psc','Aqr','Cet','Tri','PsA','Ser','Eri','Cnc','Crt','CVn','Sge','Vel','Pup','Gru','Pav','TrA','Phe','Ara','Lup','Mus','Hyi','Tuc','Col',
          'Sct','CrA','Com','LMi','Lac','Lyn','Vul','Mon','Sex','Equ','Cam','Ind','Dor','Ret','Hor','Pic','Cae','For','Scl','Mic','Tel','Nor','Cir','Aps','Cha','Vol','Men','Oct','Ant','Pyx'],
  // Rough sky region, shown inside the card details.
  region: { north:'far north (circumpolar from mid-northern latitudes)', mid:'mid-sky (both hemispheres)', south:'far south (circumpolar from mid-southern latitudes)' },

  meaning: {
    And:'the Chained Princess', Ant:'the Air Pump', Aps:'the Bird of Paradise', Aql:'the Eagle', Aqr:'the Water Bearer', Ara:'the Altar', Ari:'the Ram', Aur:'the Charioteer', Boo:'the Herdsman', CMa:'the Great Dog', CMi:'the Little Dog', CVn:'the Hunting Dogs', Cae:'the Chisel', Cam:'the Giraffe', Cap:'the Sea Goat', Car:'the Keel', Cas:'the Queen', Cen:'the Centaur', Cep:'the King', Cet:'the Sea Monster', Cha:'the Chameleon', Cir:'the Compasses', Cnc:'the Crab', Col:'the Dove', Com:'Berenice\'s Hair', CrA:'the Southern Crown', CrB:'the Northern Crown', Crt:'the Cup', Cru:'the Southern Cross', Crv:'the Crow', Cyg:'the Swan', Del:'the Dolphin', Dor:'the Swordfish', Dra:'the Dragon', Equ:'the Little Horse', Eri:'the River', For:'the Furnace', Gem:'the Twins', Gru:'the Crane', Her:'the Hero', Hor:'the Clock', Hya:'the Water Snake', Hyi:'the Little Water Snake', Ind:'the Indian', LMi:'the Little Lion', Lac:'the Lizard', Leo:'the Lion', Lep:'the Hare', Lib:'the Scales', Lup:'the Wolf', Lyn:'the Lynx', Lyr:'the Lyre', Men:'the Table Mountain', Mic:'the Microscope', Mon:'the Unicorn', Mus:'the Fly', Nor:'the Set Square', Oct:'the Octant', Oph:'the Serpent Bearer', Ori:'the Hunter', Pav:'the Peacock', Peg:'the Winged Horse', Per:'the Hero (Perseus)', Phe:'the Phoenix', Pic:'the Painter\'s Easel', PsA:'the Southern Fish', Psc:'the Fishes', Pup:'the Stern', Pyx:'the Compass', Ret:'the Reticle', Scl:'the Sculptor', Sco:'the Scorpion', Sct:'the Shield', Ser:'the Serpent', Sex:'the Sextant', Sge:'the Arrow', Sgr:'the Archer', Tau:'the Bull', Tel:'the Telescope', TrA:'the Southern Triangle', Tri:'the Triangle', Tuc:'the Toucan', UMa:'the Great Bear', UMi:'the Little Bear', Vel:'the Sails', Vir:'the Maiden', Vol:'the Flying Fish', Vul:'the Fox'
  },

  // Named asterisms & pointer hops that stitch the sky together (taught in the cards below).
  hops: [
    { from:'UMa', to:'UMi', text:'Merak → Dubhe (the Pointers): extend 5× their separation to reach Polaris.' },
    { from:'UMa', to:'Boo', text:'Follow the curve of the handle: "arc to Arcturus".' },
    { from:'Boo', to:'Vir', text:'Keep the same curve past Arcturus: "spike to Spica".' },
    { from:'UMa', to:'Leo', text:'Pointers backwards (away from Polaris) punch a hole in the Lion\'s body.' },
    { from:'UMa', to:'Cas', text:'Through Polaris and the same distance again: the W of Cassiopeia.' },
    { from:'Ori', to:'CMa', text:'Belt line down-left (south-east) → Sirius.' },
    { from:'Ori', to:'Tau', text:'Belt line up-right (north-west) → Aldebaran, then the Pleiades.' },
    { from:'Ori', to:'Gem', text:'Rigel → Betelgeuse and keep going → Castor & Pollux.' },
    { from:'Ori', to:'CMi', text:'Betelgeuse and Sirius make an equilateral triangle with Procyon (the Winter Triangle).' },
    { from:'Cas', to:'And', text:'The deeper V of the W points toward the Andromeda Galaxy.' },
    { from:'Cas', to:'Per', text:'From the shallow end of the W, drop down the Milky Way to Perseus.' },
    { from:'Lyr', to:'Cyg', text:'Vega → Deneb (the two brightest stars of the Summer Triangle).' },
    { from:'Cyg', to:'Aql', text:'Along the Milky Way south from Deneb to Altair.' },
    { from:'Sco', to:'Sgr', text:'East of the Scorpion\'s tail sits the Teapot.' },
    { from:'Cru', to:'Cen', text:'The two brilliant Pointers next to the Cross are α and β Centauri.' },
    { from:'Cru', to:'Oct', text:'The long axis of the Cross × 4.5 → the south celestial pole (no bright pole star).' },
    { from:'Peg', to:'And', text:'Andromeda hangs off the north-east corner of the Great Square.' },
    { from:'Peg', to:'PsA', text:'Drop a line down the west side of the Square → Fomalhaut.' },
  ],

  c: {
    UMa: { tag:'the Big Dipper lives here', deck:'north', best:'April – June (evening); circumpolar north of ~40°N',
      cue:'Seven bright stars: a bowl of four and a bent handle of three. The two bowl stars farthest from the handle are the Pointers. The handle\'s middle star is a double (Mizar & Alcor) to the naked eye.',
      find:'From mid-northern latitudes it never sets. Look north: high in spring evenings, low and scraping the horizon in autumn.',
      story:'The Dipper is only the bear\'s hindquarters and tail. The full Bear sprawls over three times that area with faint paws to the south.',
      confuse:['UMi','Boo'] },
    UMi: { tag:'Polaris marks the pole', deck:'north', best:'Circumpolar; highest in June evenings',
      cue:'A smaller, fainter dipper whose handle bends the opposite way. Polaris is the last star of the handle. Only Polaris, Kochab and Pherkad (the two "Guardians" at the bowl\'s end) are easy to see.',
      find:'Pointers of the Big Dipper (Merak → Dubhe), extend 5× → Polaris. Polaris\' altitude above the horizon equals your latitude.',
      story:'Polaris sits within 1° of the north celestial pole, so the whole sky wheels around it. It is not especially bright: 2nd magnitude, about 50th in the sky.',
      confuse:['UMa','Dra'] },
    Cas: { tag:'the W (or M)', deck:'north', best:'October – December; circumpolar north of ~30°N',
      cue:'Five stars in a squashed W. One V of the W is deeper than the other. Sits in the Milky Way on the opposite side of Polaris from the Big Dipper.',
      find:'Big Dipper → Polaris → keep going the same distance. When the Dipper is low, Cassiopeia is high, and vice versa.',
      story:'The vain queen was placed in the sky on her throne, condemned to hang upside down half the year.',
      confuse:['Cep','Per'] },
    Cep: { tag:'a child\'s drawing of a house', deck:'north', best:'September – November; circumpolar',
      cue:'A square with a pointed roof: five moderately faint stars. The roof peak points roughly toward Polaris. Alderamin is the brightest corner.',
      find:'Between Cassiopeia and the head of Draco. Look on the Polaris side of Cassiopeia.',
      story:'King of Aethiopia, husband of Cassiopeia. Delta Cephei is the prototype Cepheid variable, the "standard candle" that measures galaxy distances.',
      confuse:['Cas','Lac'] },
    Dra: { tag:'the winding dragon', deck:'north', best:'June – August; circumpolar',
      cue:'A long faint zigzag wrapping around the Little Dipper, ending in a compact quadrilateral head (Eltanin and Rastaban are its "eyes") near Vega.',
      find:'Its head sits between Vega and the Little Dipper\'s bowl. Its body snakes between the two Dippers.',
      story:'Thuban, mid-body, was the pole star when the pyramids were built (~2700 BCE).',
      confuse:['UMi','Cep'] },

    Ori: { tag:'the anchor of winter', deck:'winter', best:'December – February',
      cue:'Three equally-spaced belt stars in a short straight line, framed by a big rectangle: Betelgeuse (orange-red) at one corner diagonally opposite Rigel (blue-white). A faint sword hangs off the belt.',
      find:'You will not need help: in winter evenings it is the brightest pattern in the south (north of the equator) or the north (south of it).',
      story:'The belt is the universal pointer: down-left to Sirius, up-right to Aldebaran. Learn Orion and the whole winter sky opens up.',
      confuse:['Gem','Her'] },
    Tau: { tag:'the V and the Pleiades', deck:'winter', best:'December – January',
      cue:'A V-shaped face (the Hyades cluster) with orange Aldebaran glaring at the tip of one arm. Two long horns extend from the V. The tiny dipper-shaped Pleiades sits just beyond the V.',
      find:'Orion\'s belt, extended up-right, hits Aldebaran and then the Pleiades.',
      story:'Zeus as a white bull carried Europa across the sea. Aldebaran means "the follower": it follows the Pleiades across the sky.',
      confuse:['Ori','Ari'] },
    Gem: { tag:'two stick figures side by side', deck:'winter', best:'January – March',
      cue:'Two parallel lines of stars, each capped by a bright star: Castor (white) and Pollux (slightly brighter, golden). The feet dip toward Orion.',
      find:'Draw a line from Rigel through Betelgeuse and keep going: it reaches Castor and Pollux.',
      story:'The inseparable twins. Pollux is the nearer and brighter; Castor is a six-star system.',
      confuse:['Ori','Cnc'] },
    Aur: { tag:'the pentagon with Capella', deck:'winter', best:'December – February',
      cue:'A large lopsided pentagon. Capella, yellow and 6th brightest star, is the brightest corner. A tight little triangle of faint stars ("the Kids") snuggles next to Capella.',
      find:'Almost straight above Orion, at the top of the winter sky. Its bottom corner (Elnath) is shared with Taurus\' horn.',
      story:'The charioteer carries a goat (Capella = "little she-goat") and her kids on his arm.',
      confuse:['Gem','Per'] },
    CMa: { tag:'Sirius, the brightest star', deck:'winter', best:'January – February',
      cue:'Sirius is the dazzling white star. Below it a triangle of stars marks the dog\'s hindquarters (Adhara, Wezen, Aludra).',
      find:'Orion\'s belt, extended down-left, lands on Sirius.',
      story:'The Dog Star. Its summer dawn rising marked the Nile flood: hence the "dog days".',
      confuse:['CMi','Lep'] },
    CMi: { tag:'Procyon and one friend', deck:'winter', best:'January – March',
      cue:'Basically two stars: bright Procyon and fainter Gomeisa a short way off. That is the whole pattern.',
      find:'Procyon, Sirius and Betelgeuse make the near-equilateral Winter Triangle. Procyon is the eastern corner.',
      story:'Procyon means "before the dog": it rises just before Sirius.',
      confuse:['CMa','Gem'] },
    Lep: { tag:'the hare under the hunter', deck:'winter', best:'January',
      cue:'A small crooked quadrilateral with two short "ears", directly below Orion.',
      find:'Just below Rigel and Saiph, Orion\'s feet.',
      story:'The hare crouches beneath the hunter, chased by his big dog.',
      confuse:['CMa','Col'] },
    Per: { tag:'the curved hero', deck:'winter', best:'November – January',
      cue:'A curved chain of stars like a wishbone or a bent Y, with Mirfak at the crook. Algol, "the Demon Star", blinks from 2nd to 3rd magnitude every 2.87 days.',
      find:'Between Cassiopeia and the Pleiades, in the Milky Way. The Double Cluster lies between Perseus and Cassiopeia.',
      story:'Perseus carries the head of Medusa (Algol is her winking eye).',
      confuse:['Cas','Aur','And'] },
    Eri: { tag:'the long river', deck:'winter', best:'December – January',
      cue:'A faint meandering line that starts next to Rigel and wanders south and west in big loops, ending at brilliant Achernar far in the south.',
      find:'Its source is Cursa, just north-west of Rigel. Follow the faint stars downwards.',
      story:'Achernar ("river\'s end") is only visible south of ~33°N. It is the flattest star known, spinning near breakup.',
      confuse:['Hya','Cet'] },
    Col: { tag:'the dove below the hare', deck:'winter', best:'January (needs a clear southern horizon)',
      cue:'A small flattened kite: Phact and Wazn are the two brightest points.',
      find:'Directly below Lepus, low in the south from northern latitudes.',
      story:'Noah\'s dove, released from the Ark (Argo Navis lies to the east).',
      confuse:['Lep','Pup'] },

    Leo: { tag:'the Sickle', deck:'spring', best:'March – May',
      cue:'A backwards question mark (the Sickle) with Regulus as the dot, plus a right triangle to the east ending in Denebola. Unusually, it actually looks like a crouching lion.',
      find:'Big Dipper Pointers backwards (away from Polaris) → the Lion.',
      story:'The Nemean lion slain by Hercules. Regulus lies almost exactly on the ecliptic, so the Moon and planets pass right by it.',
      confuse:['Boo','Vir'] },
    Vir: { tag:'spike to Spica', deck:'spring', best:'April – June',
      cue:'A sprawling Y with blue-white Spica at the bottom of the stem. The rest is faint: the Y opens toward Leo.',
      find:'Arc along the Big Dipper\'s handle to Arcturus, then continue the curve to Spica.',
      story:'The goddess of the harvest holding an ear of wheat (Spica). The Virgo Cluster of galaxies sits in the bowl of the Y.',
      confuse:['Leo','Boo'] },
    Boo: { tag:'the kite with Arcturus', deck:'spring', best:'May – July',
      cue:'A tall kite or ice-cream cone with orange Arcturus (4th brightest star) at the pointed bottom.',
      find:'Arc to Arcturus: follow the Big Dipper\'s handle curve about one handle-length.',
      story:'The herdsman who drives the bears around the pole. Arcturus means "bear guard".',
      confuse:['Her','Vir'] },
    Cnc: { tag:'the faint crab', deck:'spring', best:'February – April',
      cue:'An upside-down Y of faint stars. The prize is the Beehive cluster (M44), a naked-eye smudge at the center.',
      find:'Between Castor/Pollux and Regulus; there is a gap of nothing bright and that gap is Cancer.',
      story:'The crab that Hera sent to pinch Hercules. It got stepped on. Faintest of the zodiac.',
      confuse:['Gem','LMi'] },
    CrB: { tag:'a tiara of seven stars', deck:'spring', best:'June',
      cue:'A neat semicircle of stars, the brightest (Alphecca) at the center of the arc. Small and unmistakable.',
      find:'Just east of Boötes\' kite, between Arcturus and Vega.',
      story:'Ariadne\'s wedding crown, tossed into the sky by Dionysus.',
      confuse:['Boo','Her'] },
    Hya: { tag:'the longest constellation', deck:'spring', best:'March – April',
      cue:'A compact head of five or six stars south of Cancer, then a body that trails 100° eastward. Alphard, "the solitary one", is the single bright star with nothing near it.',
      find:'The head lies below Cancer; Alphard is south-west of Regulus. Corvus and Crater ride on its back.',
      story:'The many-headed water snake killed by Hercules. Whenever one head was cut off, two grew back.',
      confuse:['Eri','Ser'] },
    Crv: { tag:'the sail', deck:'spring', best:'April – May',
      cue:'A small, skewed quadrilateral (like a spinnaker) of four 3rd-magnitude stars. The two top stars point toward Spica.',
      find:'South-west of Spica. Look for a compact box below Virgo.',
      story:'Apollo\'s crow, sent for water, dawdled to eat figs, and was flung into the sky next to the cup he can never drink from.',
      confuse:['Crt','Lib'] },
    Crt: { tag:'the cup', deck:'spring', best:'April',
      cue:'A faint goblet: a small quadrilateral base with two curving arms opening upward. Dimmer and larger than Corvus.',
      find:'Just west of Corvus, on the back of Hydra.',
      story:'Apollo\'s cup, kept just out of the thirsty crow\'s reach.',
      confuse:['Crv','Sex'] },
    CVn: { tag:'Cor Caroli under the handle', deck:'spring', best:'May',
      cue:'Two stars, that is all: Cor Caroli and fainter Chara, tucked under the Big Dipper\'s handle.',
      find:'Directly below the arc of the Big Dipper\'s handle.',
      story:'Named for Charles I\'s heart. Hosts the Whirlpool Galaxy near the end of the Dipper\'s handle.',
      confuse:['Com','UMa'] },

    Lyr: { tag:'Vega with a parallelogram', deck:'summer', best:'July – September',
      cue:'Blazing blue-white Vega with a small neat parallelogram of four fainter stars hanging off it. Tiny but very distinctive.',
      find:'Vega is the brightest star overhead on summer evenings (north). It is the sharp corner of the Summer Triangle.',
      story:'Orpheus\' harp. Vega was the pole star 12,000 years ago and will be again in 12,000 years.',
      confuse:['Cyg','Del'] },
    Cyg: { tag:'the Northern Cross', deck:'summer', best:'August – October',
      cue:'A large cross lying along the Milky Way: Deneb at the top (tail), Albireo at the foot (beak), with the wings spreading across. The swan flies down the Milky Way.',
      find:'Deneb is the fainter, north-eastern corner of the Summer Triangle.',
      story:'Deneb is a supergiant ~2,600 light years away, one of the most luminous stars you can see. Albireo is a gold-and-blue double in any telescope.',
      confuse:['Lyr','Aql'] },
    Aql: { tag:'Altair with two escorts', deck:'summer', best:'August – September',
      cue:'Bright Altair with a fainter star on each side in a short straight line (Tarazed and Alshain). The rest of the eagle is a flattened diamond.',
      find:'Southern corner of the Summer Triangle, south of Cygnus along the Milky Way.',
      story:'Zeus\' eagle. Altair spins so fast it is squashed, completing a rotation in under 9 hours.',
      confuse:['Cyg','Del'] },
    Sco: { tag:'the fishhook with Antares', deck:'summer', best:'June – August',
      cue:'A long J or fishhook curving down and back up to a stinger pair (Shaula & Lesath). Red Antares glows in the "heart", flanked by two fainter stars. Three stars in a vertical row mark the head/claws.',
      find:'Low in the south on summer evenings (north). High overhead from the southern hemisphere.',
      story:'The scorpion that killed Orion; the gods placed them at opposite ends of the sky so they never meet. Antares = "rival of Mars".',
      confuse:['Sgr','Ser'] },
    Sgr: { tag:'the Teapot', deck:'summer', best:'July – August',
      cue:'Eight stars making a teapot: a triangular lid, a handle on the east, a spout on the west. The Milky Way "steam" rises from the spout: that is the centre of our galaxy.',
      find:'Just east (left, in the north) of Scorpius\' tail, low in the south.',
      story:'A centaur archer aiming at the Scorpion\'s heart. Sagittarius A*, the galaxy\'s black hole, sits just off the spout.',
      confuse:['Sco','Cap'] },
    Her: { tag:'the Keystone', deck:'summer', best:'June – August',
      cue:'A trapezoid of four medium stars (the Keystone) with limbs sprawling from each corner. No bright star. M13, the great globular cluster, sits on the western edge of the Keystone.',
      find:'Between Vega and Arcturus; the Keystone is about a third of the way from Vega.',
      story:'Hercules kneeling, upside-down from the north. Ras Algethi, his head, is next to Rasalhague, the head of Ophiuchus.',
      confuse:['Boo','Oph'] },
    Oph: { tag:'the big house between Scorpius and Hercules', deck:'summer', best:'July',
      cue:'A large, faint pentagon like an elongated house with Rasalhague at the peak. It sits directly above Antares.',
      find:'Between the Keystone of Hercules (north) and Scorpius (south). Its feet stand on the scorpion.',
      story:'Asclepius, the healer, holding a snake (Serpens): the origin of the medical symbol. The Sun crosses it every December, the "13th sign".',
      confuse:['Her','Ser'] },
    Ser: { tag:'the snake in two halves', deck:'summer', best:'June – July',
      cue:'Split by Ophiuchus: Serpens Caput (head), a small triangle plus a line west of Ophiuchus; Serpens Cauda (tail), a line east of it stretching toward Aquila.',
      find:'Head: between Corona Borealis and Ophiuchus, with Unukalhai as its brightest. Tail: runs from Ophiuchus toward Altair.',
      story:'The only constellation in two disconnected pieces.',
      confuse:['Oph','Hya'] },
    Del: { tag:'job\'s Coffin', deck:'summer', best:'August – September',
      cue:'A tiny tight diamond of four stars with a fifth trailing off as a tail. Looks like a kite or dolphin leaping.',
      find:'Just east of Altair. Small enough to hide behind your thumb.',
      story:'The dolphin that persuaded Amphitrite to marry Poseidon. Sualocin and Rotanev are "Nicolaus Venator" spelled backwards, an astronomer\'s prank.',
      confuse:['Sge','Lyr'] },
    Sge: { tag:'the tiny arrow', deck:'summer', best:'August',
      cue:'A short line with a small fork at one end: an arrow. Third-smallest constellation.',
      find:'Between Altair and Albireo, inside the Summer Triangle.',
      story:'Cupid\'s arrow, or the one Hercules used on the eagle gnawing at Prometheus.',
      confuse:['Del','Aql'] },
    Lib: { tag:'the scales', deck:'summer', best:'June',
      cue:'A quadrilateral of faint stars, like a kite, between Spica and Antares. Zubenelgenubi and Zubeneschamali are the brightest corners.',
      find:'Between Virgo (Spica) and Scorpius (Antares).',
      story:'Originally the claws of the Scorpion; its star names still mean "southern claw" and "northern claw".',
      confuse:['Crv','Sco'] },
    Cap: { tag:'the smile', deck:'summer', best:'September',
      cue:'A broad flattened triangle (a smile, or a bikini bottom) of faint stars. No bright star. Algedi at the western tip is a naked-eye double.',
      find:'East of the Teapot; south-east of Altair by about the length of the Summer Triangle.',
      story:'Pan, half goat half fish. Neptune was discovered here in 1846.',
      confuse:['Sgr','Aqr'] },

    Peg: { tag:'the Great Square', deck:'autumn', best:'September – November',
      cue:'A huge nearly-empty square of four 2nd-magnitude stars. From the square, a neck and head (ending in Enif) stretch to the south-west and two legs to the north-west.',
      find:'High in the south on autumn evenings (north). The Square\'s corners are ~15° apart.',
      story:'The winged horse born from Medusa\'s blood. Its north-east corner (Alpheratz) officially belongs to Andromeda.',
      confuse:['And','Her'] },
    And: { tag:'two arms from the Square', deck:'autumn', best:'October – December',
      cue:'Two diverging curved lines of stars stretching from Alpheratz (the Square\'s NE corner) toward Perseus. Mirach and Almach are the bright anchors of the lower line.',
      find:'Follow the north-east corner of the Great Square. The Andromeda Galaxy (M31) is a smudge above Mirach.',
      story:'The chained princess rescued by Perseus. M31 is the farthest thing visible to the naked eye, 2.5 million light years.',
      confuse:['Peg','Per'] },
    Ari: { tag:'three stars in a bent line', deck:'autumn', best:'November – December',
      cue:'Just three stars in a short crooked line: Hamal (brightest), Sheratan, and faint Mesarthim close beside it.',
      find:'Between the Pleiades and the Great Square; below Triangulum.',
      story:'The golden-fleeced ram. The Sun\'s position at the spring equinox was here 2,000 years ago (the "first point of Aries").',
      confuse:['Tri','Tau'] },
    Psc: { tag:'the Circlet and a V', deck:'autumn', best:'October – November',
      cue:'A big faint V with a small ring (the Circlet) at one end, wrapping around the south and east of the Great Square.',
      find:'The Circlet sits just below the Great Square. The knot (Alrescha) is far to the south-east.',
      story:'Aphrodite and Eros turned into fish, tied together so they would not lose each other.',
      confuse:['Aqr','Cet'] },
    Aqr: { tag:'the Water Jar', deck:'autumn', best:'September – October',
      cue:'Faint and sprawling. The recognisable bit is the Water Jar: a tiny Y of four stars. Streams of faint stars flow south-east from it to Fomalhaut.',
      find:'South of the Great Square and east of Capricornus. Sadalsuud and Sadalmelik are its brightest.',
      story:'Ganymede pouring water for the gods. The stream ends in the mouth of the Southern Fish.',
      confuse:['Cap','Psc'] },
    Cet: { tag:'the sea monster', deck:'autumn', best:'November – December',
      cue:'Large: a pentagon head near Aries, a long body, and Diphda (Deneb Kaitos) as a lone bright star at the tail. Mira in the neck swells from invisible to 2nd magnitude over 11 months.',
      find:'Below Aries and Pisces, south-east of the Great Square.',
      story:'The monster sent to devour Andromeda, turned to stone by Perseus.',
      confuse:['Eri','Psc'] },
    Tri: { tag:'the little triangle', deck:'autumn', best:'November',
      cue:'A slim, sharp isosceles triangle of three modest stars. Small and simple.',
      find:'Between Andromeda\'s lower line and Aries.',
      story:'Home of M33, the Triangulum Galaxy, third member of our Local Group.',
      confuse:['Ari','And'] },
    PsA: { tag:'the lonely star', deck:'autumn', best:'October (low in the south from the north)',
      cue:'Fomalhaut, a 1st-magnitude star with nothing bright anywhere near it, plus a faint ring of stars for the fish\'s body.',
      find:'Drop a line down the western edge of the Great Square, about 45°.',
      story:'Fomalhaut is 25 light-years away and has a directly imaged debris disk.',
      confuse:['Gru','Aqr'] },

    Cru: { tag:'the Southern Cross', deck:'south', best:'April – June (southern hemisphere; below ~25°N)',
      cue:'Four bright stars in a compact kite shape with a fifth fainter one inside. Smallest constellation. Acrux at the foot is the brightest; Gacrux at the top is orange. The dark Coalsack nebula sits beside it.',
      find:'The two brilliant Pointers (α and β Centauri) always point at it. Beware the larger, dimmer False Cross to the west.',
      story:'Extend the long axis 4.5× from Gacrux through Acrux to find the south celestial pole.',
      confuse:['Vel','Car','Mus'] },
    Cen: { tag:'the Pointers', deck:'south', best:'April – June (south)',
      cue:'Two brilliant stars close together: Alpha Centauri (yellow, 3rd brightest star) and Beta Centauri (Hadar, blue). The rest is a large sprawling figure wrapping around Crux.',
      find:'The Pointers lie just east of the Southern Cross.',
      story:'Alpha Centauri is the nearest star system, 4.3 light years away. Omega Centauri, the largest globular cluster, is a fuzzy naked-eye star in the body.',
      confuse:['Cru','Lup'] },
    Car: { tag:'Canopus and the False Cross', deck:'south', best:'February – March (south)',
      cue:'Canopus, second brightest star, blazes alone. To its east, the False Cross (two Carina + two Vela stars) is bigger, dimmer and more symmetric than Crux, and has no Pointers.',
      find:'Canopus is ~35° south of Sirius. Follow the Milky Way from Crux toward Canopus.',
      story:'The keel of the ship Argo, which was broken into three constellations (Carina, Vela, Puppis).',
      confuse:['Cru','Vel'] },
    Vel: { tag:'the sails', deck:'south', best:'March (south)',
      cue:'A rough irregular hexagon of 2nd-magnitude stars in the Milky Way. Two of them form half of the False Cross.',
      find:'Between Crux/Centaurus and Canopus, north-west of Carina.',
      story:'The sails of Argo. Gamma Velorum is the brightest Wolf-Rayet star.',
      confuse:['Car','Pup'] },
    Pup: { tag:'the stern', deck:'south', best:'February (south)',
      cue:'A long spray of faint-to-medium stars in the Milky Way, south-east of Sirius. Naos is the brightest.',
      find:'Between Sirius and Canopus.',
      story:'The rear of the Argo. Deep-sky rich, few bright stars.',
      confuse:['Vel','CMa'] },
    Gru: { tag:'the crane', deck:'south', best:'September – October (south)',
      cue:'A bright line of stars with a bend, like a flying crane\'s neck. Alnair and Beta Gruis (red) are the two brightest. Two close pairs of faint stars mark the neck.',
      find:'Directly south of Fomalhaut.',
      story:'One of the "Southern Birds" added by Dutch navigators in the 1590s.',
      confuse:['PsA','Phe'] },
    Pav: { tag:'the peacock', deck:'south', best:'August (south)',
      cue:'The bright star Peacock at one end and a loose scatter of fainter stars forming a wedge.',
      find:'Between the Southern Triangle and the south celestial pole region.',
      story:'Another southern bird, named for Hera\'s sacred animal.',
      confuse:['TrA','Ind'] },
    TrA: { tag:'the Southern Triangle', deck:'south', best:'July (south)',
      cue:'A bold, almost equilateral triangle of three 2nd-3rd magnitude stars. Bigger and brighter than Triangulum.',
      find:'Just south-east of the Pointers (α/β Centauri).',
      story:'Atria, its brightest star, is an orange giant.',
      confuse:['Cru','Ara'] },
    Phe: { tag:'the phoenix', deck:'south', best:'November (south)',
      cue:'Ankaa (bright) at one end and a small quadrilateral of fainter stars, between Achernar and Fomalhaut.',
      find:'Between Achernar and Fomalhaut.',
      story:'The bird that rises from its ashes. Look for it rising in southern spring.',
      confuse:['Gru','Scl'] },
    Ara: { tag:'the altar', deck:'south', best:'July (south)',
      cue:'A compact rectangle of stars in the Milky Way, just south of the Scorpion\'s tail.',
      find:'Directly below Scorpius\' stinger.',
      story:'The altar on which the gods swore allegiance before fighting the Titans.',
      confuse:['TrA','Sco'] },
    Lup: { tag:'the wolf', deck:'south', best:'June (south)',
      cue:'A tangle of medium stars between the Pointers and Scorpius. No obvious shape: recognise it by its location.',
      find:'Between Beta Centauri and Antares.',
      story:'A wild beast impaled on the Centaur\'s spear.',
      confuse:['Cen','Sco'] },
    Mus: { tag:'the fly', deck:'south', best:'May (south)',
      cue:'A small skewed shape of four or five stars just south of the Southern Cross.',
      find:'Directly below Crux, on the side away from the Pointers.',
      story:'The only insect in the sky, buzzing beneath the Cross.',
      confuse:['Cru','Cha'] },
    Hyi: { tag:'the little water snake', deck:'south', best:'December (south)',
      cue:'A long thin triangle of three stars between Achernar and the Small Magellanic Cloud.',
      find:'Just south of Achernar.',
      story:'Not to be confused with Hydra, the huge northern-ish snake.',
      confuse:['Tuc','Hya'] },
    Tuc: { tag:'the toucan', deck:'south', best:'November (south)',
      cue:'A faint scatter with one 3rd-magnitude star. Recognise it by its treasures: the Small Magellanic Cloud and the great globular 47 Tucanae.',
      find:'Between Achernar and the south celestial pole, south of Grus.',
      story:'Named by Dutch navigators for the big-beaked bird of the New World.',
      confuse:['Hyi','Gru'] },
  }
};
